name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          yarn install --cwd example --frozen-lockfile
          yarn install --frozen-lockfile
      - name: Lint JavaScript files
        run: yarn lint

  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          yarn install --cwd example --frozen-lockfile
          yarn install --frozen-lockfile
      - name: Run typescript
        run: yarn typescript

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            */**/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: |
          yarn install --cwd example --frozen-lockfile
          yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test --coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            */**/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: |
          yarn install --cwd example --frozen-lockfile
          yarn install --frozen-lockfile
      - name: Build package
        run: yarn prepare
